# Generated by Django 4.0.3 on 2025-07-18 07:46

import apps.sample.models
from django.db import migrations, models
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_alter_feature_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دامنه'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[apps.sample.models.validate_image_or_svg], verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='gallerysitesample',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
    ]
