# Generated by Django 4.0.3 on 2025-04-22 10:52

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0003_alter_authormagmodel_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mag',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='صوتی'),
        ),
        migrations.AddField(
            model_name='mag',
            name='description_audio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='authormagmodel',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 22, 10, 52, 14, 258097, tzinfo=utc), null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='groupmagmodel',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='magmainslider',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
