# Generated by Django 4.0.3 on 2025-04-22 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0004_mag_audio_mag_description_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormagmodel',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 22, 11, 5, 36, 225752, tzinfo=utc), null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='groupmagmodel',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='صوتی'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='magmainslider',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
