# Generated by Django 4.0.3 on 2025-06-15 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0006_alter_authormagmodel_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormagmodel',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 15, 6, 39, 33, 298798, tzinfo=utc), null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='groupmagmodel',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='صوتی'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='magmainslider',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
