# Generated by Django 4.2.19 on 2025-03-23 18:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='نوع موضوع')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ اپدیت')),
                ('city', models.TextField(blank=True, null=True, verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'درباره شرکت',
                'verbose_name_plural': 'درباره شرکت',
            },
        ),
        migrations.CreateModel(
            name='MetaTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.BooleanField(default=True, verbose_name='ایندکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'متا تگ درباره من',
                'verbose_name_plural': 'متا تگ\u200cهای درباره من',
            },
        ),
        migrations.CreateModel(
            name='SchemaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('text_field', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='2توضیحات')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.aboutus', verbose_name='درباره من')),
            ],
            options={
                'verbose_name': 'Schema Code',
                'verbose_name_plural': 'Schema Codes',
            },
        ),
        migrations.CreateModel(
            name='ItemGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='گزینه')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ اپدیت')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_about', to='about.aboutus', verbose_name='صفحه')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس گالری',
            },
        ),
        migrations.CreateModel(
            name='GalleryAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس صفحه اصلی')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ اپدیت')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_image', to='about.aboutus', verbose_name='صفحه')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری درباره ما',
            },
        ),
    ]
