# Generated by Django 4.0.3 on 2025-07-08 10:43

from django.db import migrations, models
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_galleryabout_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryabout',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس صفحه اصلی'),
        ),
    ]
