# Generated by Django 4.0.3 on 2025-03-23 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 23, 21, 0, 57, 793091, tzinfo=utc), null=True, verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='videoservice',
            name='file_video',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, verbose_name='ویدیو'),
        ),
    ]
