# Generated by Django 4.0.3 on 2025-04-22 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_faq_register_date_alter_plan_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 22, 10, 52, 14, 238833, tzinfo=utc), null=True, verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='videoservice',
            name='file_video',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, verbose_name='ویدیو'),
        ),
    ]
