# Generated by Django 4.0.3 on 2025-06-15 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_faq_register_date_alter_plan_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 15, 6, 39, 33, 282840, tzinfo=utc), null=True, verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='videoservice',
            name='file_video',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, verbose_name='ویدیو'),
        ),
        migrations.CreateModel(
            name='ServiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='تصویر گالری')),
                ('alt_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='متن جایگزین تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='service.service', verbose_name='سرویس مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر گالری سرویس',
                'verbose_name_plural': 'گالری سرویس\u200cها',
            },
        ),
    ]
