# Generated by Django 4.2.19 on 2025-03-23 18:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(max_length=100, verbose_name='نوع درخواست')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'نوع تماس',
                'verbose_name_plural': 'انواع تماس',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('title_time', models.CharField(max_length=100, verbose_name='زمان تماس')),
                ('link_city', models.TextField(blank=True, null=True, verbose_name='آدرس شهر')),
                ('type_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='call.typecall', verbose_name='نوع تماس')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
            },
        ),
    ]
