# Generated by Django 4.2.19 on 2025-03-23 18:49

import apps.company.models
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام شرکت')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره شرکت')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('image_name', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[apps.company.models.validate_image_or_svg], verbose_name='لوگو تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات شرکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, null=True, verbose_name='سوال')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='جواب')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('video', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان صفحه اصلی')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='آدرس عکس صفحه اصلی')),
                ('video_name', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='آدرس ویدیو صفحه اصلی')),
                ('link_button', models.TextField(verbose_name='آدرس لینک')),
                ('anchor_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن لینک')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه اصلی',
                'verbose_name_plural': 'اطلاعات صفحه\u200cهای اصلی',
            },
        ),
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.BooleanField(default=True, verbose_name='ایندکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تگ متا',
                'verbose_name_plural': 'تگ\u200cهای متا',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_title', models.CharField(max_length=100, verbose_name='نام شبکه اجتماعی')),
                ('link', models.TextField(verbose_name='لینک')),
                ('svg_link', models.TextField(verbose_name='آدرس SVG')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='why_us_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 23, 18, 49, 47, 225686, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ ثبت ')),
            ],
            options={
                'verbose_name': 'زیر مجموعه چرا ما ',
                'verbose_name_plural': 'زیر مجموعه چرا ما',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('image_name', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[apps.company.models.validate_image_or_svg], verbose_name='لوگو تصویر')),
            ],
            options={
                'verbose_name': 'دلیل انتخاب',
                'verbose_name_plural': 'دلایل انتخاب',
            },
        ),
        migrations.CreateModel(
            name='a_href',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_link', models.CharField(max_length=1000, verbose_name='لینک ادرس')),
                ('anker', models.CharField(max_length=100, verbose_name='متن لنگر')),
                ('why', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_why2', to='company.why_us_2', verbose_name='چرا ما')),
            ],
        ),
    ]
