# Generated by Django 4.0.3 on 2025-07-18 07:46

import apps.company.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_customer_alter_why_us_2_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': ' اطلاعات مشتریان '},
        ),
        migrations.AlterField(
            model_name='company',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[apps.company.models.validate_image_or_svg], verbose_name='لوگو تصویر'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ویدیو'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='آدرس عکس صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='video_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='آدرس ویدیو صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='why_us_2',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 18, 7, 46, 56, 429008, tzinfo=utc), null=True, verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[apps.company.models.validate_image_or_svg], verbose_name='لوگو تصویر'),
        ),
    ]
