# Generated by Django 5.1.1 on 2025-02-09 13:52

import apps.whyUs.models
import django.db.models.deletion
import django.utils.timezone
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_c', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
            ],
            options={
                'verbose_name': 'شرکا',
                'verbose_name_plural': 'شرکا',
            },
        ),
        migrations.CreateModel(
            name='Member_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('who', models.CharField(max_length=100, verbose_name='سمت در شرکت')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='موضوع پلن')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('image_name', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[apps.whyUs.models.validate_image_or_svg], verbose_name='نام فایل')),
            ],
            options={
                'verbose_name': 'پلن پایه ',
                'verbose_name_plural': 'پلن پایه  ها',
            },
        ),
        migrations.CreateModel(
            name='Resum_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='متن')),
                ('answer', models.TextField(verbose_name='جواب متن')),
                ('ress', models.CharField(blank=True, max_length=10, null=True, verbose_name='جواب متن')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
            ],
            options={
                'verbose_name': 'رزومه شرکت',
                'verbose_name_plural': 'رزومه های شرکت',
            },
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='کلمه')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
            ],
            options={
                'verbose_name': ' سرویس ',
                'verbose_name_plural': 'لیست سرویس ها در بنر',
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('is_checked', models.BooleanField(default=True, verbose_name='check')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_item', to='whyUs.plan', verbose_name='پلن')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(verbose_name='ایکون')),
                ('link', models.TextField(verbose_name='لینک ادرس')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_social', to='whyUs.member_company', verbose_name='عضو')),
            ],
        ),
    ]
