# Generated by Django 4.2.19 on 2025-03-03 05:01

import apps.whyUs.models
from django.db import migrations, models
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('whyUs', '0009_alter_collaboration_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='member_company',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[apps.whyUs.models.validate_image_or_svg], verbose_name='نام فایل'),
        ),
    ]
