# Generated by Django 5.1.1 on 2025-07-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_message_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
