# Generated by Django 4.0.3 on 2025-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_is_seen_alter_message_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='sms_sent',
            field=models.BooleanField(default=False, verbose_name='پیامک ارسال شده؟'),
        ),
    ]
